M48
; DRILL file {KiCad (6.0.6)} date Sun Oct 16 14:55:53 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-16T14:55:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.0079Y-2.0433
X6.0079Y-4.4134
X6.8425Y-2.0433
X6.8425Y-4.4134
T0
M30
