M48
; DRILL file {KiCad (6.0.6)} date Sun Nov 13 22:02:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-13T22:02:18-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.7598Y-1.811
X3.7598Y-3.7795
X7.3228Y-1.811
X7.3228Y-3.7795
T0
M30
