M48
; DRILL file {KiCad (6.0.6)} date Sun Dec 25 11:50:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-25T11:50:32-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.225Y-1.4
X1.25Y-8.525
X5.7Y-2.85
X9.7Y-2.85
X12.2491Y-2.15
X14.5669Y-8.55
X14.5787Y-2.1496
T0
M30
